### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by Surakarus** [qjon/angular2-filemanager#1]
I tried to figure out how upload works, but failed. Could you please help me?

**Comment by Surakarus** [comment]
I figured it out, it's because of fsevents compatibility.

**Comment by Surakarus** [comment]
But i still want to know how to upload files.

**Comment by Surakarus** [comment]
I receive this error
`Error: Error in ./Toolbar class Toolbar - inline template:7:6 caused by: item is undefined`

**Comment by qjon** [comment]
Hi, did you look at example? Is that demo works? Could you send me more details about your problem, because I can not reproduce this issue?

**Comment by Surakarus** [comment]
Hello!
I got this error when upload button is pressed in demo.
Also I can't understand how user should select files to upload. Is it drag&drop or what?
What details do you need?
Thank you in advance

**Comment by qjon** [comment]
Oh, it's looks strange (in my clear build it works). Pressing upload button in toolbar should open system dialog and let you choose files from your system (standard browser window). Currently there is no D&D functionality but I can fink about it in the future. 
Hmm... Let's check if we do the same steps:
1. Clone repo
2. npm i
3. In first terminal: npm run backend
4. In second terminal: npm start
5. Open browser: http://localhost:4200

This steps allows me to create directory and upload files. Did you do the same steps?

**Comment by Surakarus** [comment]
I usually use Mozilla Firefox as default browser, and dialog window doesn't appears in it. But if I open localhost:4200 in Chrome, upload works perfectly.
And yes, I followed exactly these steps.

**Comment by qjon** [comment]
OK. So this is some issue in FF, I will check it. Thanks for feedback.

**Comment by Surakarus** [comment]
Sorry for not mentioning the fact: This error appears if I manually call `fileManagerUploader.uploader.onUpload()`.
I know that this is wrong, but I was desperate.
Without this mess there is only `[WDS] Disconnected!` warning.
And dialog window doesn't show.
Sorry again.

**Comment by Surakarus** [comment]
I solved this problem using RMD's answer
http://stackoverflow.com/questions/39132451/can-i-use-ng2-file-upload-with-button-instead-of-a-file-input 
Hope it helps someone
