### ISSUE TITLE
Not able to integrate this plugin in my angular 2 based project

### ISSUE THREAD

**Issue by gotephodevishal** [qjon/angular2-filemanager#19]
Hi Rafal,
I am trying to integrate this plugin in my angular 2 based project. I followed the declaration structure as mentioned in [Demo](https://github.com/qjon/angular2-filemanager/tree/master/demo/src/app) example. npm is throwing error when **FileManager** module is imported in @NgModule 
After adding FileManagerModule in @NgModule import section I am always getting errors as-
```
ERROR in ./src/app/admin/admin.module.ts
Module not found: Error: Can't resolve '@rign/angular2-filemanager/main' in 'myproject\src\app\admin'
resolve '@rign/angular2-filemanager/main' in 'myproject\src\app\admin'
  Parsed request is a module
using description file: myproject\package.json (relative path: ./src/app/admin)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: myproject\package.json (relative path: ./src/app/admin)
    resolve as module
myproject\node_modules doesn't exist or is not a directory.
```

**Comment by qjon** [comment]
Hi,

Demo used internal src directory to import FilemanagerModule. In you project you should install @rign/angular2-filemanager in latest version (currently, 1.3.0) and import all package elements form '@rign/angular2/tree', so it should like:

`import {FilemanagerModule} from '@rign/angular2-filemanager`

Please, give me feedback if I have right

**Comment by gotephodevishal** [comment]
Thanks Rafal. You are right. I was trying import modules from 
`import {FilemanagerModule} from '@rign/angular2-filemanager/main'`

**Comment by gotephodevishal** [comment]
Hi @qjon ,
Sorry to disturb you again but need your help in 2 issues.
1. Now when running that file manager page in browser console gives an **StaticInjectorError** as below -
![screenshot_1](https://user-images.githubusercontent.com/34640265/37030726-0e92f858-2162-11e8-9ac0-c6c209a20283.jpg)

2. can you explain or guide me, how to implement the back-end API side functionality to link tree folder structure to blob storage

**Comment by qjon** [comment]
Ad. 1.
It seems that you miss some other modules that have to be initialized:

```
imports: [
  ...,
  BrowserAnimationsModule,
  ConfirmationPopoverModule.forRoot(),
  EffectsModule.forRoot([]),
  FileManagerModule.forRoot(fileManagerConfiguration),
  StoreModule.forRoot({}),
  TreeModule.forRoot(),
  TranslateModule.forRoot(),
]
```


Ad.2 You have to implement on your backend endpoint to get list of items like this one

```
interface IOuterNode {
    id: string;
    treeId?: string;
    name: string;
    parentId?: string | null;
    children?: Array<string>;
    parents?: Array<string>;
}
```

Also endpoint for files should return list of items like

```
interface IOuterFile {
    id: string | number;
    folderId?: string;
    name: string;
    thumbnailUrl: string;
    url: string;
    width: number;
    height: number;
    type: string;
    data?: string;
    size?: number;
    selected?: boolean;
}

```

**Comment by qjon** [comment]
Duplicated comment #20
