### ISSUE TITLE
I can't make it work with my existing configurations of angular-4 app!

### ISSUE THREAD

**Issue by zbeedatm** [qjon/angular2-filemanager#21]
Hi,
I'm trying to use this component in my app...

I had angular 4.2.4 , cli 1.4.9 and typescript 2.3.3, and was getting:

![image](https://user-images.githubusercontent.com/26740851/37558734-34e5612c-2a21-11e8-887a-e7c23ee2276e.png)

Tried upgrading to angular 4.4.6 with same cli 1.4.9 and typescript 2.5.3 but it didn't help. and now I'm getting:

![image](https://user-images.githubusercontent.com/26740851/37558851-3a2ac152-2a23-11e8-91ae-6e2e968cece0.png)

this is my [pakcage.json](https://gist.github.com/zbeedatm/cfeaf71b1850bfc3a41e619c0caf86fd)

Can you please advice...

**Comment by qjon** [comment]
This issue is displayed when you have two version of angular. My package require angular ^5.2.x., so you have to upgrade your application package.json.
