### ISSUE TITLE
Please can you provide a link of working demo

### ISSUE THREAD

**Issue by jessicastorm1986** [qjon/angular2-filemanager#3]
It will be so very helpful to others aswell. Thanks

**Comment by qjon** [comment]
Hi, currently I don't have any place where I can deploy it. I think of that as a feature. Now you can download repo and run example as it is described in README.

**Comment by qjon** [comment]
Hi, I've just release version 1.0.0. Currently there is [DEMO](https://qjon.github.io/angular2-filemanager/). If you will have any problems do not hesitate to contact me.
