### ISSUE TITLE
Struggling to get this to work

### ISSUE THREAD

**Issue by marcodafonseca** [qjon/angular2-filemanager#4]
I added the filemanager to my project with:
`npm i @rign/angular2-filemanager`

I then tried importing it into my component with:
`import { } from "@rign/angular2-filemanager";`
I'm not sure what to specify between the curly braces as my intellisense comes up empty and I can't find any documentation on using this tool.

In my html I have this specified:
`<div class="container">
    <h1>Document Management System</h1>
    <div class="configuration-bar">
        <button class="btn btn-primary" (click)="toggleMultiSelection()">
            <i class="fa" [ngClass]="{'fa-check-square': isMultiSelection, 'fa-square': !isMultiSelection}"></i>
            <span>Use Multiselect</span>
        </button>
    </div>
    <filemanager [multiSelection]="isMultiSelection" (onSingleFileSelect)="selectFile($event)">Loading...</filemanager>
</div>
`

and I just get the following error when I try run my project:
`Exception: Call to Node module failed with error: Error: Template parse errors:
'filemanager' is not a known element:
1. If 'filemanager' is an Angular component, then verify that it is part of this module.
2. If 'filemanager' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("
</button>
</div>
[ERROR ->]<filemanager (onSingleFileSelect)="selectFile($event)">Loading...</filemanager>
</div>`

What am I missing?

**Comment by qjon** [comment]
Hi,

There is a gap in documentation. You do everything in proper way. You should import FileManagerModule in your app. See example angular2-filemanager/demo/src/app/app.module.ts or try to run Demo on your computer as it is described in Demo section.

On the other side I currently work on change in this package to use redux (look develop branch). It is almost finished. When I will be ready, I also prepare Live Demo. I think that it could be soon.

**Comment by qjon** [comment]
I've just released version 1.0.0. I think it will be better than previous version. If you will have any problems with using it do not hesitate to contact me.
